/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Tile Tango',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 500,
      obstacleCount: 0,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 50,
      backgroundTheme: 'meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Swapping Spree',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 60,
      targetScore: 800,
      obstacleCount: 0,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 50,
      backgroundTheme: 'city',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Pattern Pursuit',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.4,
      timeLimitSeconds: 60,
      targetScore: 1200,
      obstacleCount: 0,
      obstacleSpeed: 0,
      collectibleCount: 20,
      collectibleValue: 50,
      backgroundTheme: 'forest',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Tiled Tactics',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 45,
      targetScore: 1500,
      obstacleCount: 5,
      obstacleSpeed: 2,
      collectibleCount: 25,
      collectibleValue: 75,
      backgroundTheme: 'desert',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Tile Tornado',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 45,
      targetScore: 2000,
      obstacleCount: 8,
      obstacleSpeed: 3,
      collectibleCount: 30,
      collectibleValue: 75,
      backgroundTheme: 'underwater',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Tile Tempest',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 30,
      targetScore: 2500,
      obstacleCount: 10,
      obstacleSpeed: 4,
      collectibleCount: 35,
      collectibleValue: 100,
      backgroundTheme: 'space',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Tile Typhoon',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 30,
      targetScore: 3000,
      obstacleCount: 12,
      obstacleSpeed: 5,
      collectibleCount: 40,
      collectibleValue: 100,
      backgroundTheme: 'futuristic',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Tile Tempest II',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 30,
      targetScore: 3500,
      obstacleCount: 15,
      obstacleSpeed: 5,
      collectibleCount: 45,
      collectibleValue: 100,
      backgroundTheme: 'space',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Tile Tornado II',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 20,
      targetScore: 4000,
      obstacleCount: 12,
      obstacleSpeed: 6,
      collectibleCount: 50,
      collectibleValue: 100,
      backgroundTheme: 'underwater',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Tile Tempest III',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 20,
      targetScore: 5000,
      obstacleCount: 20,
      obstacleSpeed: 6,
      collectibleCount: 55,
      collectibleValue: 100,
      backgroundTheme: 'futuristic',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
